### ISSUE TITLE
Record live stream to mp4

### ISSUE THREAD

**Issue by Haxnaat** [st1lson/FFmpeg.Net#1]
Hey Can you please help me in recording stream to mp4 using ffmpeg. How can I achieve that?

**Comment by st1lson** [comment]
> Hey Can you please help me in recording stream to mp4 using ffmpeg. How can I achieve that?

If you have a .m3u8 file, you can just use this command: <br />
```cmd
ffmpeg -i source.m3u8 -bsf:a aac_adtstoasc -vcodec copy -c copy -crf 50 output.mp4
```
If you need it, I will implement it in the wrapper

**Comment by Haxnaat** [comment]
I have rstp stream which I want to record in chunks of mp4.
`ffmpeg -i "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4" -c copy -reset_timestamps 1 -metadata title=\\”Soho1\\” -map 0 -f segment -segment_time 1:00 -segment_format mp4 "recording-%03d.mp4”`
i am using above command in terminal and its working fine. I need to implement it in c# code to make it customizable

**Comment by st1lson** [comment]
> ffmpeg -i "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4" -c copy -reset_timestamps 1 -metadata title=\\”Soho1\\” -map 0 -f segment -segment_time 1:00 -segment_format mp4 "recording-%03d.mp4”

I just finished.<br /> Check out the latest version [here ](https://www.nuget.org/packages/FFmpeg.Net/)
